### ISSUE TITLE
Japanese emoji dont support in your version

### ISSUE THREAD

**Issue by angushhz** [mathiasbynens/emoji-regex#114]
https://emojidb.org/cute-japanese-emojis
I checked and found that your regex dont match above emoji
Could it possible for you to help me explain ?

**Comment by slevithan** [comment]
There is a technical definition for Unicode emoji. See [Wikipedia: Emoji](https://en.wikipedia.org/wiki/Emoji) for details.

The page you linked to mostly shows *emoticons* rather than *emoji*. Emoticons are arbitrary character sequences that, when taken together and seen visually with the right font, could be interpreted as an image or expressing an emotion. Check out the Wikipedia pages on [emoticons](https://en.wikipedia.org/wiki/Emoticon), [ASCII art](https://en.wikipedia.org/wiki/ASCII_art), and [Shift_JIS art](https://en.wikipedia.org/wiki/Shift_JIS_art) to learn more. There is an infinite set of ways you could arrange arbitrary characters to create art or express feeling. The list of character sequences that would meet this definition is entirely subjective, but [this page](https://en.wikipedia.org/wiki/List_of_emoticons) lists some common ones. Trying to list or identify them is not the job of a regex designed to match only/all emoji.

**Comment by angushhz** [comment]
Thank you for your replies
