### ISSUE TITLE
Some Apple emoji do not match

### ISSUE THREAD

**Issue by flipstewart** [mathiasbynens/emoji-regex#2]
:relaxed:, :one:, and :heart: for example.

I'm sure there's a reason for this, but my app needs them to match.

Would you consider an optional parameter that would also match these characters? Maybe something like:

```js
emojiRegex({includeNotTechnicallyEmojiCharacters: true});
```

I'd be happy to put the PR in, just wanted to check if this is a desirable feature.

**Comment by luin** [comment]
+1

**Comment by mathiasbynens** [comment]
> I'm sure there's a reason for this […]

For the record, the reason is [this one](https://github.com/mathiasbynens/unicode-tr51#readme) (emphasis added):

> _unicode-tr51_ contains data extracted from [the `emoji-data.txt` file](http://www.unicode.org/Public/emoji/1.0/emoji-data.txt) that is part of [Unicode Technical Report #51](http://www.unicode.org/reports/tr51/). ***Specifically, the data lists all emoji symbols that lack a text equivalent.***

`1️⃣` is `'1\uFE0F\u20E3'`, i.e. 1 followed by a variation selector, followed by COMBINING ENCLOSING KEYCAP. Since U+0031 U+20E3 appears in the emoji data text file, this would match [after stripping variation selectors from the input](https://github.com/mathiasbynens/strip-variation-selectors), if unicode-tr51 didn’t specifically exclude emoji that have a textual representation by default. Perhaps that should change, though.

**Comment by mathiasbynens** [comment]
Fixed.
