### ISSUE TITLE
Some basic emojis does not match

### ISSUE THREAD

**Issue by mahmoodkohansal** [mathiasbynens/emoji-regex#38]
Hi, I'm using your library to match emojis. the problem is about matching some emojis I think are standard emojis. some of them is listed below:

- 🏳️ White Flag U+1F3F3
- ☺️ Smiling Face U+263A
- ☹️ Frowning Face U+2639

Does the library matched with them? Is there any way to add them to regex?

**Comment by mathiasbynens** [comment]
* U+1F3F3 WHITE FLAG is an `Emoji` symbol but not an `Emoji_Presentation` symbol (see [`emoji-data.txt`](https://unicode.org/Public/emoji/latest/emoji-data.txt)), meaning that according to the Unicode Standard it’s supposed to render as text by default. To force its emoji form, the standard requires it to be followed by U+FE0F VARIATION SELECTOR-16.
* U+263A SMILING FACE: same as above.
* U+2639 FROWNING FACE: same as above.

I know macOS and iOS render these even without the U+FE0F, but they shouldn’t. It would not be feasible for this project to maintain a list of macOS’s violations of the Unicode Standard, especially because other platforms might do the same thing for other symbols. This project follows the Unicode Standard and as such this is working as intended.
