### ISSUE TITLE
does not match trailing VARIATION SELECTOR-16

### ISSUE THREAD

**Issue by rodneyrehm** [mathiasbynens/emoji-regex#45]
Following up on this [tweet](https://twitter.com/rodneyrehm/status/1039188775065276416):

I'm using emoji-regex to identify if the last symbol of a string is an emoji. While this works for most emojis, it does not for `⚽️`. As it turns out this is happening because macOS inserts [`U+26BD`](https://www.fileformat.info/info/unicode/char/26bd/index.htm) followed by [`U+FE0F`](https://www.fileformat.info/info/unicode/char/fe0f/index.htm) and that trailing variation selector is *not* part of the emoji-regex match.

While I don't think this is a *bug* in emoji-regex I do believe emoji-regex could help avoid this situation by including the unnecessary variation selector in the match.

**Comment by jcubic** [comment]
I think it's a bug because unicode without variation selector is just text and it there is variation selector after it should be rendered as image that only then it should be match as emoji.

I have another issue, What about pizza symbol:

`🍕️`,  `"\ud83c\udf55\ufe0f"` https://emojipedia.org/slice-of-pizza/

U+1F355 U+FE0F

is this emoji with variation selector a valid emoji sequence? Becasue it matches only first two surrogate pair and ignore variation selector.

**Comment by jcubic** [comment]
Oh, thanks, I was not sure about this one.

**Comment by mathiasbynens** [comment]
macOS and iOS emoji input has recently improved to be more in line with the spec. I'm hoping Apple has solved (or will continue to solve) this problem so that we don't need to work around it in emoji-regex.

For your use case, you could check if the string ends with a variation selector, and remove it before further processing the string.
